### ISSUE TITLE
Boa sorte!

### ISSUE THREAD

**Issue by ruanSignori** [RaunyGL/hackaween-equipe-saw#2]
Senhores, lhe desejo boa sorte no hacka
O @Lusqinha ele faz tudo, desde design até levantar muro, portanto, qualquer coisa é só pedir pra ele fazer
aproveitem a comida grátis, é o mínimo, e vou voltar aqui após 12 horas, espero que vocês vençam
![@Lusqinha ](https://github.com/user-attachments/assets/cca49480-811a-478d-9903-29358b5f38b4)

Se a criatividade estiver bloqueada, ou estiver sob pressão para terminar a apresentação, espero que esse hino motivacional os ajude a enfrentar os problemas.
[Vídeo motivacional para hackaton](https://www.youtube.com/watch?v=B3gAZvncfa0&list=RDB3gAZvncfa0&start_radio=1)

**Comment by ruanSignori** [comment]
PARABÉNS GUYS
![20170629235019257494e](https://github.com/user-attachments/assets/8b8c7690-0d77-4449-b984-a3e317afc36c)

**Comment by Lusqinha** [comment]
Muito obrigado Ruan, tu é meu herói
